# Remote Machine Configuration for manage.py
# This file defines remote machines that can be managed via SSH

machines:

  - name: "superheavy"
    host: "superheavy"              # Hostname or IP address
    user: "brian"                    # SSH username (optional, uses current user if not specified)
    port: 22                         # SSH port (default: 22)
    key_file: "/home/brian/.ssh/id_rsa"  # Path to SSH private key (optional)
    use_agent: true                  # Use SSH agent if available (default: true)
    timeout: 10                      # Connection timeout in seconds (default: 10)
    enabled: true                    # Set to false to disable without deleting

  - name: "backup"
    host: "backup"              # Hostname or IP address
    user: "brian"                    # SSH username (optional, uses current user if not specified)
    port: 22                         # SSH port (default: 22)
    key_file: "/home/brian/.ssh/id_rsa"  # Path to SSH private key (optional)
    use_agent: true                  # Use SSH agent if available (default: true)
    timeout: 10                      # Connection timeout in seconds (default: 10)
    enabled: true                    # Set to false to disable without deleting

  - name: "docker"
    host: "docker"              # Hostname or IP address
    user: "brian"                    # SSH username (optional, uses current user if not specified)
    port: 22                         # SSH port (default: 22)
    key_file: "/home/brian/.ssh/id_rsa"  # Path to SSH private key (optional)
    use_agent: true                  # Use SSH agent if available (default: true)
    timeout: 10                      # Connection timeout in seconds (default: 10)
    enabled: true                    # Set to false to disable without deleting

