# SOPS configuration for encrypting secrets
# This file defines which machines can decrypt which secrets

creation_rules:
  # Secrets specific to superheavy machine
  - path_regex: secrets/superheavy\.yaml$
    # Replace with actual public key after generating keys
    # Format: age1...
    age: |
      # TODO: Add superheavy public key here
      # Run: cat secrets/keys/superheavy.age.pub
  
  # Secrets specific to brian-laptop machine
  - path_regex: secrets/brian-laptop\.yaml$
    # Replace with actual public key after generating keys
    age: |
      # TODO: Add brian-laptop public key here
      # Run: cat secrets/keys/brian-laptop.age.pub
  
  # Secrets shared across all machines
  - path_regex: secrets/common\.yaml$
    # Add all machine public keys here
    age: |
      # TODO: Add all machine public keys here (comma-separated)
      # Example: age1abc...,age1def...

